### ISSUE TITLE
Default branch after clone

### ISSUE THREAD

**Issue by seba--** [pluto-build/build-git#2]
The default branch of the working copy after a clone is determined by HEAD of the remote and should be set accordingly. Currently, the working copy simply uses master as default branch.

https://github.com/pluto-build/build-git/blob/master/src/build/pluto/buildgit/util/GitHandler.java#L53

**Comment by seba--** [comment]
The current implementation leads to an error here: https://github.com/pluto-build/build-pluto/blob/master/src/build/pluto/buildpluto/CompileSourceCode.java#L88

The problem is that after the initial cloning of `origin/java7`, the working copy only has a branch `master`. A subsequent checkout of `java7` fails.

**Comment by andrepacak** [comment]
Should be resolved by 2bc7721806a89f550622f06a9a9ec65816eabb27.
